/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Userschema {
  firstName?: {
    type?: string;
    [k: string]: any;
  };
  lastName?: {
    type?: string;
    [k: string]: any;
  };
  age?: {
    description?: string;
    type?: string;
    minimum?: number;
    [k: string]: any;
  };
  hairColor?: {
    enum?: string[];
    type?: string;
    [k: string]: any;
  };
  [k: string]: any;
}
